### ISSUE TITLE
Two addresses in same park

### ISSUE THREAD

**Issue by vukisz** [algirdasc/hass-eparkai#1]
My situation:

![Image](https://github.com/user-attachments/assets/ea131750-4f76-407b-921c-b7aa4cc5c507)

My yaml config
``` yaml
eparkai: 
  username: !secret eparkai_login
  password: !secret eparkai_pass
  client_id: !secret eparkai_client_id
  power_plants:
  - name: Eparkai power plant 01
    id: !secret eparkai_plant_01_id
    object_address: !secret eparkai_plant_01_address_01
  - name: Eparkai power plant 02
    id: !secret eparkai_plant_01_id
    object_address: !secret eparkai_plant_01_address_02
```

Result shows only power plant 02:

![Image](https://github.com/user-attachments/assets/2fbb680c-994d-4e86-9ead-09ddb811382c)

Also data shown in plant 02 is from park 01 address.

![Image](https://github.com/user-attachments/assets/16c199d9-0686-4895-aea4-ef7410f33a9e)

Edit: tried using statistics_id_suffix. Now I got two statistics, but both shows power plant 01 address 01 data.  No power plant 01 address 02 data.
